<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseCategory;

/**
 * The Category class maps the 'categories' table in database.
 */
class Category extends BaseCategory
{
}
