<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseItem;

/**
 * The Item class maps the 'items' table in database.
 */
class Item extends BaseItem
{
}
