<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseCategoryDao;

/**
 * The CategoryDao class will maintain the persistence of Category class into the categories table.
 */
class CategoryDao extends BaseCategoryDao
{
}
