<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseItemDao;

/**
 * The ItemDao class will maintain the persistence of Item class into the items table.
 */
class ItemDao extends BaseItemDao
{
}
